### PR TITLE
added GetCheckResults and GetCheckResult

### LINKED ISSUE #5: Add CheckResult type and functions to ListCheckResults & RetrieveCheckResult
We have a use case of the checkly sdk where we need to retrieve the last check result to update the state of the server. In order to achieve this, the following needs to be added:

1. A type on `CheckResult` to model the response of this request https://www.checklyhq.com/docs/api/#retrieve-a-check-result. 
2. A function that makes the call to the above endpoint to retrieve a check request
3. A function that makes a call to the endpoint https://www.checklyhq.com/docs/api/#lists-all-check-results to retrieve a list of all check requests for a check

### PR DESCRIPTION
**Pull request by kjda**
fixes #5

### CODE REVIEW

**Comment by umutuzgur** [comment]
@kjda The code looks good but I don't like that we created a separate file called `get-check-result.go`. I suggest doing one of the two things, either just add the code in `get-check-result.go` to `checkly.go` as a quick fix or we refactor the code base and create an `api` folder and create files corresponding to the api types, e.g. `groups.go` and `check-results.go`.

**Comment by kjda** [comment]
> @kjda The code looks good but I don't like that we created a separate file called `get-check-result.go`. I suggest doing one of the two things, either just add the code in `get-check-result.go` to `checkly.go` as a quick fix or we refactor the code base and create an `api` folder and create files corresponding to the api types, e.g. `groups.go` and `check-results.go`.

I think having a group of endpoints into one file reduces visibility a lot, especially when the number of implementations increase, it's also not easy to isolate testing for a single endpoint.. putting those into separate files was a first step towards refactoring the whole checkly.go file, i thought we refactor the rest in a next step, or should we do it as part of this pr?

**Comment by umutuzgur** [comment]
I think we are on the same page about what we want to do. I'm not a fan of refactor + feature in the same PR. I would prefer to add it in checkly.go temporarily and then send the refactor PR as a second step

**Comment by kjda** [comment]
> I think we are on the same page about what we want to do. I'm not a fan of refactor + feature in the same PR. I would prefer to add it in checkly.go temporarily and then send the refactor PR as a second step

yes, that's the point, there was no refactoring, just having new code ready for future improvement.. anyways, I moved it to checkly.go & will update PR now

**Pull request merged**
