### PR TITLE
JSON fixes for optional fields

### PR DESCRIPTION
**Pull request by devillexio**
This PR includes fixes for the following issues:
- #13 
- #14

### CODE REVIEW

**Comment by umutuzgur** [comment]
Hey @devillexio, thanks for sending the PR. Our APIs follow the Stripe PUT/PATCH style. This means omiting everything that is empty or null will prevent people from nulling their settings or sending an empty `tags` field to remove their existing `tags` in a check. This will sadly break, especially, our PUT requests. I will see how we can address this in the backend

**Comment by pastjean** [comment]
Hi @umutuzgur,
Stripe go SDK does make everything optional by putting everything other than slices as pointer. This makes it so the "zero-value"  is the one to reset. and null is the one to not change a value. There are no `omitempty` in Stripe's go api though. 

I believe that part of @devillexio PR is good (turning stuff into pointers). Where the omit empty might indeed not work with how you expect the API to behave.

**Comment by devillexio** [comment]
I don't mind making changes in line with what the Checkly API expects. When this is merged, my hope is to have consensus on the behaviour between this client and the Checkly API documentation. That would help prevent some of the issues we've seen in testing over the last few days, i.e. seeing API errors when a `null` value is passed instead of no value at all.

Also, it would be good if you would consider expanding the [Checkly API documentation](https://www.checklyhq.com/docs/api#checkly-api) to provide guidance on:
- when to set fields to empty values, and
- when to omit them.

The way I interpreted the documentation was that anything marked with _(required)_ would need a value in every request, and everything else could be omitted.

**Comment by kjda** [comment]
thanks for the PR. having optional fields as pointers is the way to go, we did this in a recent refactor for some fields as a first step.. I hope I can get all those as pointers in the next refactor without breaking things

**Pull request merged**
