### PR TITLE
feat: add x-checkly-source header [sc-00]

### PR DESCRIPTION
**Pull request by ndom91**
## Affected Components
* [ ] New Features
* [ ] Bug Fixing
* [ ] Types
* [ ] Tests
* [ ] Docs
* [x] Other

## Style
* [x] Go code is formatted with `go fmt`

## Notes for the Reviewer

Added the new `x-checkly-source` header to the API calls for tracking in Segment / downstream data sources. 

For API additions, see: https://github.com/checkly/checkly-backend/pull/2511

Terraform addition: https://github.com/checkly/terraform-provider-checkly/pull/109

### CODE REVIEW

**Comment by umutuzgur** [comment]
@ndom91 I agree. I think we should allow the client to override the header so terraform provider can set a different header.

**Comment by ndom91** [comment]
As golang doesn't seem to have optional parameters or default values, how would yuo recommend doing this? I dont know the first thing about golang unfortunately :sweat_smile:

**Comment by ianaya89** [comment]
@ndom91 I think we should follow a similar approach as we did when adding support for AccountID. 

Basically, add a new `source` property to our `Client` type and add a setter method that could be used to define this property. 


If the property is not present we can set a default (like `go-sdk`) or directly avoid the header.

**Comment by ndom91** [comment]
Thanks a lot @ianaya89! How does this look? Then in the terraform provider we can set it via `client.SetChecklySource = 'TF'`, no?

**Review by umutuzgur — APPROVED** [review]
LGTM

**Pull request merged**
